### ISSUE TITLE
[CONCEPT] Two ideas about the processing of .yml collections file

### ISSUE THREAD

**Issue by michealespinola** [alex-phillips/plex-autocollections#25]
Hi!  I've been experimenting with the script and I love it.  This makes [re]building and propping-up my Plex server so much easier.  However, I have a movie database of ~1500 movies, and there are some issues regarding the collections.yml as it exists in the codebase.  I get quite a few "false" matches because of the looseness of the processing of the collections.yml file.  

My first thought is:  If we are using Plex which is scraping official names/dates from a  centralized source - why aren't we being more specific about our matching criteria?  As an easy example, even "^The Avengers$" isn't precise for the movie in the Marvel Cinematic Universe, where there is a "The Avengers" of the same name from 1998.  Granted, the 1998 movie is horrible but could easily be in someone's collection.  It is/was *cough* in mine.  :-)  This is just one example of multiple mismatches I experienced with the default collections.yml set.

Scraping is easy, and it seems to me to really dial-in this tool (and I actually hate using that phrase), that a little more specificity in the collections should be easy and worthwhile for the long run.  I strongly think that exact name matching should be possible (i.e allow colons, etc) and that matching the release year should be inforced.  Adding an optional third field for an IMDB ID# would be ideal.  There are frequently multiple movies a year that come out with the same name and also same release year.  As an example, 2006 has multiple movies called "The Bridge".  Granted, this example is not mainstream or common with big movies, but the possibility exists.  Especially amongst documentaries.

My second thought is:  Everyone has their own idea of what constitutes a "collection".  I think it would be more accessible to have individual collection files for each individual collection, so people can more easily mix-and-match their own.  They can download what they want (if they don't want to create/edit their own), and let the script process through multiple collection files that suit their needs/tastes.

I'm privately working on both of these concepts but my python skills are quite basic, and I thought I'd pass these ideas up the chain to see if anyone else thought they made sense.

In any event, thank you for sharing this script with the rest of us.  [Re]building collections can be such a chore!

**Comment by alex-phillips** [comment]
Thanks for the feedback! I like your ideas.

First, the reason I added in the regex matching rather than exact matching in Plex is for a couple of reasons.
1. Not everybody may use the same agents to match their media.
2. Some people change their movie titles manually for personal preference. I know that I have many title overrides that relate directly to different versions of a movie (i.e., Director's Cut or different Star Wars releases).

I added in the date enforcement to attempt to curb some of the 'false positives' that the script can cause (ex: Alice in Wonderland cartoon vs the newer 'series' of 2 movies).

I'm not sure if exact title matching is the direction I want to go here. But I do like the idea of adding in an optional IMDB ID and if it exists, willy only match those movies found in your library. Another option is we could build out the library with IMDB IDs for every item and have a flag that tells the script to run and honor the IDs or to not honor them.

I've love to chat more about improving this to better handle incorrect matches, but I do think that loose title matching is important.

**Comment by tomhoover** [comment]
@alex-phillips, I just submitted a [HUGE PR](#26) to add Hallmark Movies collection(s) -- this is probably too specialized, and large, to add to the master `collections.yml` file. 

Going along with @michealespinola's second idea listed above, what would your thoughts be to add a `collections.d` directory alongside `collections.yml`? The idea would be to process any supplemental `.yml` files contained within that directory when running the autocollections script. If that is a direction you'd be amenable to go, I wouldn't mind revising the script to process the additional files.

**Comment by alex-phillips** [comment]
@tomhoover I like it!

**Comment by tomhoover** [comment]
@michealespinola's second idea is implemented by #27.

**Comment by michealespinola** [comment]
Thanks, guys for implementing my idea!  I've just recently been testing it [mostly] successfully and have opened issue #36 to reflect my initial findings of using the new feature.

**Comment by alex-phillips** [comment]
I think we can close this since #36 was merged in.
