### ISSUE TITLE
Install to a Docker?

### ISSUE THREAD

**Issue by seanap** [alex-phillips/plex-autocollections#3]
Hey, I'm having a hard time getting this to find my Plex username.  My plex server is running in a docker on Ubuntu.  I've tried running this script on my windows pc, and I've moved the files into the actual plex docker config folder and tried running from the terminal there.  I keep getting "NameError: name 'myusername' is not defined".

**Comment by alex-phillips** [comment]
When do you get this error? Does it prompt you and are you able to enter your Plex username and password?

**Comment by lonix** [comment]
Im haveing the same problem, and in my case it asks for username and throws:

`╰ python main.py
Plex Username: lonix
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    plex = Plex()
  File "main.py", line 10, in __init__
    self.account = self.get_account()
  File "<decorator-gen-2>", line 2, in get_account
  File "/usr/local/lib/python2.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/usr/local/lib/python2.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "main.py", line 17, in get_account
    username = input("Plex Username: ")
  File "<string>", line 1, in <module>
NameError: name 'lonix' is not defined`

where lonix is input username

**Comment by SethGower** [comment]
Not sure if this got fixed, but I have no problems using this when I am running in a Docker container. Running:
- Plex version 1.13.0.5023
- Docker Version: 18.03.1-ce
- Ubuntu: 17.10
- Commit: a6a072f300af4b7b721f4ae681dede8ec403e42e

**Comment by Vikinge** [comment]
Can I run this pyhthon from inside a docker container against Synology package?  I installed all requirements in a working ubuntu docker container, but like above after I enter username it crashes with: 
'  File "main.py", line 66, in <module>
    plex = Plex()
  File "main.py", line 10, in __init__
    self.account = self.get_account()
  File "<decorator-gen-2>", line 2, in get_account'

Although even if I can solve this issue, will I be able to run this against a plex located outside the container I am running within?  If I can point to a plex IP I think it might work, otherwise I need to look for another solution.  I don't want to install all these requirements on my Synology root.

**Comment by alex-phillips** [comment]
@lonix The error you are seeing is due to your version of python. I will update the readme, but this project doesn't work with 2, only 3.

**Comment by alex-phillips** [comment]
@Vikinge I think you're issue may also be related to the python version. Try 3 instead of 2. Also, it should still work even if the Plex instance is outside the container since this actually talks to the Plex servers to determine the publicly accessible access point. So your instance will have to be available outside the network for this to run (at least for now).

**Comment by Vikinge** [comment]
I used plexAPI plexapi.server instead of plexapi.myplex and got it to run under Python 2.7.  Using a token and IP instead of authentication worked great.  Thank you for the great script.

**Comment by alex-phillips** [comment]
@Vikinge good to know! I'll add that to the README.

@seanap did python3 fix the issue for you? (or @Vikinge above workaround?)

**Comment by alex-phillips** [comment]
Closing this as I believe it is fixed. If it's not, I can re-open.
